export const CONFIG_SCHEMA_VERSION = "2.0.0";

export const DEFAULT_CONFIG = Object.freeze({
  risk: {
    maxPositions: 3,
    maxDeployAmount: 50,
  },
  screening: {
    minFeeActiveTvlRatio: 0.05,
    minTvl: 10_000,
    maxTvl: 150_000,
    minVolume: 500,
    minOrganic: 60,
    minHolders: 500,
    minMcap: 150_000,
    maxMcap: 10_000_000,
    minBinStep: 80,
    maxBinStep: 125,
    timeframe: "5m",
    category: "trending",
    minTokenFeesSol: 30,
    maxBundlePct: 30,
    maxBotHoldersPct: 30,
    maxTop10Pct: 60,
    blockedLaunchpads: [],
    minTokenAgeHours: null,
    maxTokenAgeHours: null,
    athFilterPct: null,
  },
  management: {
    minClaimAmount: 5,
    autoSwapAfterClaim: false,
    outOfRangeBinsToClose: 10,
    outOfRangeWaitMinutes: 30,
    minVolumeToRebalance: 1000,
    stopLossPct: -50,
    takeProfitFeePct: 5,
    minFeePerTvl24h: 7,
    minAgeBeforeYieldCheck: 60,
    minSolToOpen: 0.55,
    deployAmountSol: 0.5,
    gasReserve: 0.2,
    positionSizePct: 0.35,
    trailingTakeProfit: true,
    trailingTriggerPct: 3,
    trailingDropPct: 1.5,
    solMode: false,
  },
  strategy: {
    strategy: "bid_ask",
    binsBelow: 69,
  },
  schedule: {
    managementIntervalMin: 10,
    screeningIntervalMin: 30,
    healthCheckIntervalMin: 60,
  },
  llm: {
    temperature: 0.373,
    maxTokens: 4096,
    maxSteps: 20,
    managementModel: "openrouter/healer-alpha",
    screeningModel: "openrouter/hunter-alpha",
    generalModel: "openrouter/healer-alpha",
  },
});

// Parameters that can be tuned without changing the application's architecture.
export const TUNABLE_PATHS = Object.freeze([
  "risk.maxPositions",
  "risk.maxDeployAmount",
  "screening.minFeeActiveTvlRatio",
  "screening.minTvl",
  "screening.maxTvl",
  "screening.minVolume",
  "screening.minOrganic",
  "screening.minHolders",
  "screening.minMcap",
  "screening.maxMcap",
  "screening.minBinStep",
  "screening.maxBinStep",
  "screening.minTokenFeesSol",
  "screening.maxBundlePct",
  "screening.maxBotHoldersPct",
  "screening.maxTop10Pct",
  "screening.minTokenAgeHours",
  "screening.maxTokenAgeHours",
  "screening.athFilterPct",
  "management.minClaimAmount",
  "management.outOfRangeBinsToClose",
  "management.outOfRangeWaitMinutes",
  "management.minVolumeToRebalance",
  "management.stopLossPct",
  "management.takeProfitFeePct",
  "management.minFeePerTvl24h",
  "management.minAgeBeforeYieldCheck",
  "management.minSolToOpen",
  "management.deployAmountSol",
  "management.gasReserve",
  "management.positionSizePct",
  "management.trailingTriggerPct",
  "management.trailingDropPct",
  "strategy.strategy",
  "strategy.binsBelow",
]);

// Hard safety parameters are deliberately excluded from automatic tuning.
export const HARD_SAFETY_PATHS = Object.freeze([
  "risk.maxPositions",
  "risk.maxDeployAmount",
  "management.minSolToOpen",
  "management.gasReserve",
]);
